### PR TITLE
Cryptography

### PR DESCRIPTION
**Pull request by Snake-Trial**
Uses UUID4 asymmetrical encryption
Server provides public key to client

### CODE REVIEW

**Comment by Snake-Trial** [comment]
> UID4

Uses rsa asymmetrical encryption - oops

**Review by miguelvaladas — CHANGES_REQUESTED** [review]
Hi, why are we coupling the Crypt class with the Clients and Servers?

We need to decouple this logic. Ideally, the Crypt class should have around 3 methods that could all be static:
1 - Generate private and public keys (and return the pair)
2 - encrypt (similar to what you did)
3 - decrypt

That's it. There is no need to have it entangled with Client or Server classes. We need to focus on SOLID principles and try to make the application as simple as possible.

**Comment by Snake-Trial** [comment]
What do you mean by 'There is no need to have it entangled with Client or Server classes'?
This class does not reference any other classes and call any - so it isn't entangled.
Do you mean just to change function names and comments so that they don't include the names client or server?
I happy to do that, if you think it makes it simpler, but please explain your idea.
Which principles are you referring to?

**Comment by miguelvaladas** [comment]
> What do you mean by 'There is no need to have it entangled with Client or Server classes'? This class does not reference any other classes and call any - so it isn't entangled. Do you mean just to change function names and comments so that they don't include the names client or server? I happy to do that, if you think it makes it simpler, but please explain your idea. Which principles are you referring to?

I get it now, so cls means an instance of this class and we're using this to hold the private and public keys (I was confused by the names of the methods). Then Both the Client use it to encrypt/decrypt. I get it, thanks for clarifying

**Review by miguelvaladas — APPROVED** [review]
looks good, thanks

**Review by kwansinnn — APPROVED** [review]

**Pull request merged**
